Balancer: Implement claimer action
mimic-fi/v2-smart-vaults pull request #80
Opened 2023-03-04 03:04 UTC by facuspagnuolo

2023-03-06 11:33 UTC, dmf7z approved these changes

2023-03-06 11:52 UTC, dmf7z requested changes

2023-03-06 11:52 UTC, dmf7z commented on packages/balancer-fee-collector/contracts/actions/claim/Claimer.sol
> +        require(token != address(0), 'TOKEN_ADDRESS_ZERO');
I understand we cannot claim native tokens. If so,we need to add a require:
`require(!Denominations.isNativeToken(token), 'CLAIMER_NATIVE_TOKEN');`

2023-03-08 23:25 UTC, facuspagnuolo commented on packages/balancer-fee-collector/contracts/actions/claim/Claimer.sol
> +        require(token != address(0), 'TOKEN_ADDRESS_ZERO');
Good catch! Fixed now

2023-03-09 12:45 UTC, dmf7z approved these changes

2023-03-09 12:53 UTC, merged