Base: Implement permissions manager
mimic-fi/v2-smart-vaults pull request #85
Opened 2023-03-13 22:21 UTC by facuspagnuolo

2023-03-14 01:22 UTC, dmf7z requested changes

2023-03-14 01:22 UTC, dmf7z commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        IAuthorizer target = request.target;
Will the PermissiosManager have permission to execute over itself, meaning request.target = IAuthorizer(this)? Seems fine, right?

2023-03-14 02:20 UTC, facuspagnuolo commented on packages/base/contracts/permissions/PermissionsManager.sol
> +            (change.grant ? target.authorize : target.unauthorize)(change.permission.who, change.permission.what);
I added at the beginning but ended up removing it, the reason is mainly because it will require at-least 2 or 3 txs to migrate admins for example. And the main reason why having this is be able to change the permissions payout in a single tx.

2023-03-14 02:24 UTC, facuspagnuolo commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        IAuthorizer target = request.target;
Yes, check out the `Deployer` lib

2023-03-14 09:59 UTC, dmf7z commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        IAuthorizer target = request.target;
👍

2023-03-21 15:04 UTC, facuspagnuolo commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        require(account != address(0), 'REVOKE_ADDRESS_ZERO');
Ended up removing this method

2023-03-21 15:04 UTC, facuspagnuolo commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        _revokeAdminPermissions(target, address(this));
Ended up removing this method

2023-03-21 15:05 UTC, facuspagnuolo commented on packages/base/contracts/permissions/PermissionsManager.sol
> +        require(account != address(this), 'REDUNDANT_TRANSFER_ADDRESS');
Ended up removing this method

2023-03-21 16:34 UTC, merged